services:
  docs:
    image: sidicutter_local_docs
    container_name: sidicutter_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./sidicutter:/app/sidicutter:z
    ports:
      - '9000:9000'
    command: /start-docs
