services:
  docs:
    image: second_server_local_docs
    container_name: second_server_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./second_server:/app/second_server:z
    ports:
      - '9000:9000'
    command: /start-docs
