services:
  docs:
    image: yapit_hrm_local_docs
    container_name: yapit_hrm_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./yapit_hrm:/app/yapit_hrm:z
    ports:
      - '9000:9000'
    command: /start-docs
